#!/bin/bash

# Check_mk plugin to check memcached
#
#       Version 1.1
#
# 2012-11-19 FLX f@qsol.ro
#       - First  version
#
# 2013-11-28 Stephan Helas
#       - Patch to exit correctly
#
# 2017-01-30 Nokius
#       - print output to /dev/null and remove wrong lines from agent

if which nc > /dev/null && which memcached > /dev/null ; then
    echo '<<<memcached>>>'
    echo "stats" | nc localhost 11211
fi
